### ISSUE TITLE
Adding `media_ids` to options doesn't work?

### ISSUE THREAD

**Issue by faisalsayed10** [adblanc/twit-thread#10]
Hey I tried adding media_ids to a tweet option but it isn't adding those image(s) to the tweet.
```
await t.twitThread([{ text: 'hello', options: { media_ids: `a comma seperated string of media ids` } }, { text: 'hello 2' }])

**Comment by adblanc** [comment]
Hi, under the hood this module posts the `media_data` if any and use it as media_ids.
Currently you can only give 1 `media_data` (aka 1 image) per tweet, but feel free to make a PR if you need to tweet more images in 1 tweet
